[package]
name = "bunching"
version = "0.1.0"
authors = ["Eric Douglass <dougli1sqrd@gmail.com>"]
edition = "2018"

[dependencies]
rocket =  "0.4.2"
reqwest = "0.9.18"
geo = "0.12.2"
serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0"